services:
  dev:
    container_name: spiff-element-units-dev
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
      - ./module:/module
      - ./dev/bin:/integration/bin
      - ./scripts:/integration/scripts
      - ./tests:/integration/tests